export default {
  heavy_rain_begins: "Heavy rain begins to fall as you approach Sarah's house.",
  warm_light_glowing: "You can see warm light glowing from her windows, creating a cozy atmosphere against the storm.",
  early_hesitate: "You hesitate at Sarah's door, soaked from the sudden downpour.",
  early_before_knock: "Before you can knock, the door opens.",
  early_drenched: "Oh my goodness! You're absolutely drenched! Come in, come in!",
  early_pulls_inside: "Sarah pulls you inside without hesitation, her natural kindness overriding any awkwardness.",
  choice_apologetic: "I'm sorry for showing up like this",
  choice_grateful: "Thank you for rescuing me",
  choice_early_romantic: "I couldn't stay away, even in this weather",
  early_nonsense: "Nonsense! I couldn't leave you out there in this storm.",
  early_returns_towel: "Sarah disappears and returns with a warm towel and a steaming mug of hot chocolate.",
  early_warm_you_right_up: "This will warm you right up. I was just making some for myself anyway.",
  early_fireplace_talk: "You spend the afternoon talking by her fireplace, watching the rain through her windows.",
  early_forced_intimacy: "The forced intimacy of the situation brings you closer together naturally.",
  choice_perfect_afternoon: "This is the most perfect afternoon I've had in ages",
  choice_cozy_home: "I love how cozy and warm your home feels",
  choice_storm_wonderful: "The storm brought me something wonderful - time with you",
  friend_watch_concern: "Through the rain-streaked window, you see Sarah watching for you with obvious concern.",
  friend_wrap_towel: "She opens the door before you reach it, immediately wrapping you in a warm towel she had ready.",
  friend_worried: "I was so worried about you being out in this weather! I've been watching the road for you.",
  friend_watching_for_me: "You were watching for me?",
  friend_love_care: "I love how you take care of me",
  friend_hold_close: "Hold her close to warm yourself",
  friend_pull_embrace: "You pull Sarah into a warm embrace, both seeking and offering comfort from the storm.",
  friend_mmm_warm: "Mmm, you're so warm, you murmur into her hair.",
  friend_get_you_warmed: "And you're so cold! Let's get you properly warmed up, she says softly.",
  friend_leads_couch: "Sarah leads you to her couch and wraps you both in a large blanket.",
  friend_sharing_warmth: "Sitting close together, sharing warmth while the storm rages outside, feels incredibly intimate.",
  friend_gentle_kiss: "Kiss her gently while you're so close",
  friend_feels_right: "This feels so right, being here with you",
  friend_wish_storm: "I wish this storm would last all night",
  friend_kiss_softly: "You lean in and kiss Sarah softly, the intimacy of the moment making it feel natural and right.",
  friend_responds_warmly: "She responds warmly, her hand coming up to cup your cheek.",
  friend_hoping_do_that: "I've been hoping you'd do that, she whispers against your lips.",
  friend_kiss_deepens: "The kiss deepens as the rain provides a romantic soundtrack to your growing closeness.",
  intimate_at_door_robe_towel: "Sarah is already at the door with a robe and towel when you arrive, soaked from the storm.",
  intimate_knew_you_come: "I knew you'd come to me in this weather. You always do when you need comfort, she says lovingly.",
  intimate_helps_undress: "She immediately begins helping you out of your wet clothes with caring, intimate familiarity.",
  intimate_know_me_well: "You know me so well",
  intimate_come_home: "I always want to come home to you",
  intimate_let_undress: "Let her continue undressing you",
  intimate_hands_gentle: "Sarah's hands are gentle but sure as she helps you out of your wet clothes.",
  intimate_need_warmed: "We need to get you warmed up properly, she says with obvious care and desire.",
  intimate_touch_lingers: "Her touch lingers longer than necessary, her eyes dark with wanting.",
  intimate_wraps_robe: "She wraps the soft robe around you, her hands trailing over your skin as she does.",
  intimate_need_warming: "I need you to warm me up",
  intimate_fire_between: "The storm outside has nothing on the fire between us",
  intimate_shower_together: "Pull her into the shower with you",
  intimate_best_idea: "Now that's the best idea I've heard all day, Sarah purrs.",
  intimate_leads_bathroom: "She leads you to her bathroom where steam is already beginning to fog the mirrors.",
  intimate_under_hot_water: "Under the hot water, with the storm raging outside, you lose yourselves in passionate intimacy...",
  intimate_hours_later: "Hours later, wrapped together in warm towels, you listen to the rain still falling softly outside.",
  intimate_every_storm_should_end: "Every storm should end like this, Sarah sighs contentedly against your chest.",
} as const;

