export default {
  closed_now: "The coffee shop is closed right now.",
  approach_counter: "You approach the counter where Maya is working.",
  stranger_hi: "Hi there! Welcome to our coffee shop. What can I get you today?",
  stranger_smiles: "Maya smiles politely but doesn't seem to recognize you.",
  choice_order: "Order coffee ($3)",
  choice_browse: "Just looking around",
  choice_start_conversation: "Try to start a conversation",
  acquaintance_hey_regular: "Oh hey! You're becoming a regular here. The usual?",
  acquaintance_remembers: "Maya remembers you from previous visits.",
  choice_chat_work: "Chat about her work",
  choice_compliment: "Compliment her coffee skills",
  friend_greeting: "Hey %PLAYER_NAME%! Great to see you again. How's your day going?",
  friend_lights_up: "Maya's face lights up when she sees you.",
  choice_ask_day: "Ask about her day",
  choice_flirt_light: "Flirt a little",
  close_highlust_hey_gorgeous: "Hey gorgeous! You're looking particularly good today...",
  close_bites_lip: "Maya bites her lip slightly as she looks at you.",
  choice_flirt_bold: "Flirt back boldly",
  choice_suggest_meetup: "Suggest meeting after work",
  choice_order_play_cool: "Order coffee and play it cool",
  close_normal_favorite_customer: "%PLAYER_NAME%! My favorite customer. What can I make special for you today?",
  choice_surprise_order: "Ask her to surprise you",
  choice_weekend_plans: "Chat about weekend plans",
  choice_flirt_playful: "Flirt playfully",
  already_back_again: "Back again so soon? I like that!",
  already_talked_today: "You've already had a meaningful conversation with Maya today.",
  choice_order_another: "Order another coffee ($3)",
  choice_just_wanted: "Just wanted to see you",
  choice_leave: "Leave",
  start_intro_maya: "I'm Maya, by the way. I don't think we've been properly introduced.",
  start_tell_name: "You tell her your name is %PLAYER_NAME%.",
  start_nice_meet: "Nice to meet you, %PLAYER_NAME%!",
  start_seems_friendly: "Maya seems friendly and approachable.",
  choice_order_now: "Order coffee now ($3)",
  choice_ask_history: "Ask how long she's worked here",
  order_here_your_coffee: "Here's your coffee! That'll be $3.",
  order_excellent_energy: "The coffee is excellent and gives you energy.",
  order_energy_money: "Energy +15 | Money: $%MONEY%",
  order_short_money_maya: "Oh, looks like you're a bit short. No worries, maybe next time!",
  order_not_enough_money: "You don't have enough money for coffee.",
  flirt_light_line: "You always know how to make a girl smile.",
  flirt_light_blush: "Maya blushes slightly and tucks her hair behind her ear.",
  flirt_working: "Your charm is working on Maya.",
  bold_flirt_line1: "You're quite the charmer, aren't you?",
  bold_flirt_line2: "Maya leans closer across the counter.",
  bold_flirt_offwork: "I get off work at 7... just saying.",
  bold_flirt_interest: "Maya is clearly interested in you.",
  just_browsing_take_time: "Take your time! Let me know if you need anything.",
  just_browsing_back_to_work: "Maya goes back to her work behind the counter.",
  ask_work_history_answer: "I've been working here for about two years now. I love the coffee culture and meeting new people!",
  ask_work_history_enthusiasm: "Maya's enthusiasm is infectious.",
  choice_that_sounds_great: "That sounds great!",
  just_wanted_sweet: "That's so sweet! You always know how to make my day better.",
  leave_come_back: "Come back soon!",
  leave_wave: "You wave goodbye and leave the coffee shop.",
} as const;

