export default {
  save: "Speichern",
  load: "Laden",
  settings: "Einstellungen", 
  quit: "Beenden",
  continue: "Fortsetzen",
  new_game: "Neues Spiel",
  press_esc: "Drücke jederzeit ESC, um zum Menü zurückzukehren",
  save_game: "Spiel speichern",
  load_game: "Spiel laden",
  slot: "Slot",
  empty_slot: "Leerer Slot",
  no_save_data: "Keine Spieldaten",
  save_name_placeholder: "Speichername...",
  empty: "Leer",
  prev: "Zurück",
  next: "Weiter",
  esc_to_close: "ESC zum Schließen",
  categories: "Kategorien:",
  language: "Sprache",
  audio: "Audio",
  text: "Text",
  gameplay: "Spielablauf",
  reset: "Zurücksetzen",
  apply: "Übernehmen",
} as const;
