export default {
  save: "Save",
  load: "Load",
  settings: "Settings", 
  quit: "Quit",
  continue: "Continue",
  new_game: "New Game",
  press_esc: "Press ESC anytime to return to menu",
  save_game: "Save Game",
  load_game: "Load Game",
  slot: "Slot",
  empty_slot: "Empty Slot",
  no_save_data: "No save data",
  save_name_placeholder: "Save name...",
  empty: "Empty",
  prev: "Prev",
  next: "Next",
  esc_to_close: "ESC to close",
  categories: "Categories:",
  language: "Language",
  audio: "Audio",
  text: "Text",
  gameplay: "Gameplay",
  reset: "Reset",
  apply: "Apply",
} as const;
