export default {
  save: "Sauvegarder",
  load: "Charger",
  settings: "Paramètres",
  quit: "Quitter", 
  continue: "Continuer",
  new_game: "Nouvelle Partie",
  press_esc: "Appuyez sur ÉCHAP à tout moment pour revenir au menu",
  save_game: "Sauvegarder la partie",
  load_game: "Charger une partie",
  slot: "Emplacement",
  empty_slot: "Emplacement vide",
  no_save_data: "Aucune sauvegarde",
  save_name_placeholder: "Nom de la sauvegarde...",
  empty: "Vide",
  prev: "Précédent",
  next: "Suivant",
  esc_to_close: "ÉCHAP pour fermer",
  categories: "Catégories :",
  language: "Langue",
  audio: "Audio",
  text: "Texte",
  gameplay: "Jouabilité",
  reset: "Réinitialiser",
  apply: "Appliquer",
} as const;
